import { IIrregularVerbs } from "./types";

export const IRREGULAR_VERBS: IIrregularVerbs[] = [
  {
    infinitive: "be",
    pastSimple: "was, were",
    pastParticiple: "been",
    translate: "быть, являться",
  },
  {
    infinitive: "become",
    pastSimple: "became",
    pastParticiple: "become",
    translate: "становиться",
  },
  {
    infinitive: "begin",
    pastSimple: "began",
    pastParticiple: "begun",
    translate: "начинать",
  },
  {
    infinitive: "bend",
    pastSimple: "bent",
    pastParticiple: "bent",
    translate: "гнуть",
  },
  {
    infinitive: "bet",
    pastSimple: "bet",
    pastParticiple: "bet",
    translate: "держать пари",
  },
  {
    infinitive: "bite",
    pastSimple: "bit",
    pastParticiple: "bitten",
    translate: "кусать",
  },
  {
    infinitive: "blow",
    pastSimple: "blew",
    pastParticiple: "blown",
    translate: "дуть, выдыхать",
  },
  {
    infinitive: "break",
    pastSimple: "broke",
    pastParticiple: "broken",
    translate: "ломать, разбивать, разрушать",
  },
  {
    infinitive: "bring",
    pastSimple: "brought",
    pastParticiple: "brought",
    translate: "приносить, привозить, доставлять",
  },
  {
    infinitive: "build",
    pastSimple: "built",
    pastParticiple: "built",
    translate: "строить, сооружать",
  },
  {
    infinitive: "buy",
    pastSimple: "bought",
    pastParticiple: "bought",
    translate: "покупать, приобретать",
  },
  {
    infinitive: "catch",
    pastSimple: "caught",
    pastParticiple: "caught",
    translate: "ловить, поймать, схватить",
  },
  {
    infinitive: "choose",
    pastSimple: "chose",
    pastParticiple: "chosen",
    translate: "выбирать, избирать",
  },
  {
    infinitive: "come",
    pastSimple: "came",
    pastParticiple: "come",
    translate: "приходить, подходить",
  },
  {
    infinitive: "cost",
    pastSimple: "cost",
    pastParticiple: "cost",
    translate: "стоить, обходиться",
  },
  {
    infinitive: "cut",
    pastSimple: "cut",
    pastParticiple: "cut",
    translate: "резать, разрезать",
  },
  {
    infinitive: "deal",
    pastSimple: "dealt",
    pastParticiple: "dealt",
    translate: "иметь дело, распределять",
  },
  {
    infinitive: "dig",
    pastSimple: "dug",
    pastParticiple: "dug",
    translate: "копать, рыть",
  },
  {
    infinitive: "do",
    pastSimple: "did",
    pastParticiple: "done",
    translate: "делать, выполнять",
  },
  {
    infinitive: "draw",
    pastSimple: "drew",
    pastParticiple: "drawn",
    translate: "рисовать, чертить",
  },
  {
    infinitive: "drink",
    pastSimple: "drank",
    pastParticiple: "drunk",
    translate: "пить",
  },
  {
    infinitive: "drive",
    pastSimple: "drove",
    pastParticiple: "driven",
    translate: "ездить, подвозить",
  },
  {
    infinitive: "eat",
    pastSimple: "ate",
    pastParticiple: "eaten",
    translate: "есть, поглощать, поедать",
  },
  {
    infinitive: "fall",
    pastSimple: "fell",
    pastParticiple: "fallen",
    translate: "падать",
  },
  {
    infinitive: "feed",
    pastSimple: "fed",
    pastParticiple: "fed",
    translate: "кормить",
  },
  {
    infinitive: "feel",
    pastSimple: "felt",
    pastParticiple: "felt",
    translate: "чувствовать, ощущать",
  },
  {
    infinitive: "fight",
    pastSimple: "fought",
    pastParticiple: "fought",
    translate: "драться, сражаться, воевать",
  },
  {
    infinitive: "find",
    pastSimple: "found",
    pastParticiple: "found",
    translate: "находить, обнаруживать",
  },
  {
    infinitive: "fly",
    pastSimple: "flew",
    pastParticiple: "flown",
    translate: "летать",
  },
  {
    infinitive: "forget",
    pastSimple: "forgot",
    pastParticiple: "forgotten",
    translate: "забывать о (чём-либо)",
  },
  {
    infinitive: "forgive",
    pastSimple: "forgave",
    pastParticiple: "forgiven",
    translate: "прощать",
  },
  {
    infinitive: "freeze",
    pastSimple: "froze",
    pastParticiple: "frozen",
    translate: "замерзать, замирать",
  },
  {
    infinitive: "get",
    pastSimple: "got",
    pastParticiple: "got",
    translate: "получать, добираться",
  },
  {
    infinitive: "give",
    pastSimple: "gave",
    pastParticiple: "given",
    translate: "дать, подать, дарить",
  },
  {
    infinitive: "go",
    pastSimple: "went",
    pastParticiple: "gone",
    translate: "идти, двигаться",
  },
  {
    infinitive: "grow",
    pastSimple: "grew",
    pastParticiple: "grown",
    translate: "расти, вырастать",
  },
  {
    infinitive: "hang",
    pastSimple: "hung",
    pastParticiple: "hung",
    translate: "вешать, развешивать, висеть",
  },
  {
    infinitive: "have",
    pastSimple: "had",
    pastParticiple: "had",
    translate: "иметь, обладать",
  },
  {
    infinitive: "hear",
    pastSimple: "heard",
    pastParticiple: "heard",
    translate: "слышать, услышать",
  },
  {
    infinitive: "hide",
    pastSimple: "hid",
    pastParticiple: "hidden",
    translate: "прятать, скрывать",
  },
  {
    infinitive: "hit",
    pastSimple: "hit",
    pastParticiple: "hit",
    translate: "ударять, поражать",
  },
  {
    infinitive: "hold",
    pastSimple: "held",
    pastParticiple: "held",
    translate: "держать, удерживать, задерживать",
  },
  {
    infinitive: "hurt",
    pastSimple: "hurt",
    pastParticiple: "hurt",
    translate: "ранить, причинять боль, ушибить",
  },
  {
    infinitive: "keep",
    pastSimple: "kept",
    pastParticiple: "kept",
    translate: "хранить, сохранять, поддерживать",
  },
  {
    infinitive: "know",
    pastSimple: "knew",
    pastParticiple: "known",
    translate: "знать, иметь представление",
  },
  {
    infinitive: "lay",
    pastSimple: "laid",
    pastParticiple: "laid",
    translate: "класть, положить, покрывать",
  },
  {
    infinitive: "lead",
    pastSimple: "led",
    pastParticiple: "led",
    translate: "вести за собой, сопровождать, руководить",
  },
  {
    infinitive: "leave",
    pastSimple: "left",
    pastParticiple: "left",
    translate: "покидать, уходить, уезжать, оставлять",
  },
  {
    infinitive: "lend",
    pastSimple: "lent",
    pastParticiple: "lent",
    translate: "одалживать, давать взаймы (в долг)",
  },
  {
    infinitive: "let",
    pastSimple: "let",
    pastParticiple: "let",
    translate: "позволять, разрешать",
  },
  {
    infinitive: "lie",
    pastSimple: "lay",
    pastParticiple: "lain",
    translate: "лежать",
  },
  {
    infinitive: "light",
    pastSimple: "lit",
    pastParticiple: "lit",
    translate: "зажигать, светиться, освещать",
  },
  {
    infinitive: "lose",
    pastSimple: "lost",
    pastParticiple: "lost",
    translate: "терять, лишаться, утрачивать",
  },
  {
    infinitive: "make",
    pastSimple: "made",
    pastParticiple: "made",
    translate: "делать, создавать, изготавливать",
  },
  {
    infinitive: "mean",
    pastSimple: "meant",
    pastParticiple: "meant",
    translate: "значить, иметь в виду, подразумевать",
  },
  {
    infinitive: "meet",
    pastSimple: "met",
    pastParticiple: "met",
    translate: "встречать, знакомиться",
  },
  {
    infinitive: "pay",
    pastSimple: "paid",
    pastParticiple: "paid",
    translate: "платить, оплачивать, рассчитываться",
  },
  {
    infinitive: "put",
    pastSimple: "put",
    pastParticiple: "put",
    translate: "ставить, помещать, класть",
  },
  {
    infinitive: "read",
    pastSimple: "read",
    pastParticiple: "read",
    translate: "читать, прочитать",
  },
  {
    infinitive: "ride",
    pastSimple: "rode",
    pastParticiple: "ridden",
    translate: "ехать верхом, кататься",
  },
  {
    infinitive: "ring",
    pastSimple: "rang",
    pastParticiple: "rung",
    translate: "звенеть, звонить",
  },
  {
    infinitive: "rise",
    pastSimple: "rose",
    pastParticiple: "risen",
    translate: "восходить, вставать, подниматься",
  },
  {
    infinitive: "run",
    pastSimple: "ran",
    pastParticiple: "run",
    translate: "бежать, бегать",
  },
  {
    infinitive: "say",
    pastSimple: "said",
    pastParticiple: "said",
    translate: "говорить, сказать, произносить",
  },
  {
    infinitive: "see",
    pastSimple: "saw",
    pastParticiple: "seen",
    translate: "видеть",
  },
  {
    infinitive: "seek",
    pastSimple: "sought",
    pastParticiple: "sought",
    translate: "искать, разыскивать",
  },
  {
    infinitive: "sell",
    pastSimple: "sold",
    pastParticiple: "sold",
    translate: "продавать, торговать",
  },
  {
    infinitive: "send",
    pastSimple: "sent",
    pastParticiple: "sent",
    translate: "посылать, отправлять, отсылать",
  },
  {
    infinitive: "set",
    pastSimple: "set",
    pastParticiple: "set",
    translate: "устанавливать, задавать, назначать",
  },
  {
    infinitive: "shake",
    pastSimple: "shook",
    pastParticiple: "shaken",
    translate: "трясти, встряхивать",
  },
  {
    infinitive: "shine",
    pastSimple: "shone",
    pastParticiple: "shone",
    translate: "светить, сиять, озарять",
  },
  {
    infinitive: "shoot",
    pastSimple: "shot",
    pastParticiple: "shot",
    translate: "стрелять",
  },
  {
    infinitive: "show",
    pastSimple: "showed",
    pastParticiple: "shown, showed",
    translate: "показывать",
  },
  {
    infinitive: "shut",
    pastSimple: "shut",
    pastParticiple: "shut",
    translate: "закрывать, запирать, затворять",
  },
  {
    infinitive: "sing",
    pastSimple: "sang",
    pastParticiple: "sung",
    translate: "петь, напевать",
  },
  {
    infinitive: "sink",
    pastSimple: "sank",
    pastParticiple: "sunk",
    translate: "тонуть, погружаться",
  },
  {
    infinitive: "sit",
    pastSimple: "sat",
    pastParticiple: "sat",
    translate: "сидеть, садиться",
  },
  {
    infinitive: "sleep",
    pastSimple: "slept",
    pastParticiple: "slept",
    translate: "спать",
  },
  {
    infinitive: "speak",
    pastSimple: "spoke",
    pastParticiple: "spoken",
    translate: "говорить, разговаривать, высказываться",
  },
  {
    infinitive: "spend",
    pastSimple: "spent",
    pastParticiple: "spent",
    translate: "тратить, расходовать, проводить (время)",
  },
  {
    infinitive: "stand",
    pastSimple: "stood",
    pastParticiple: "stood",
    translate: "стоять",
  },
  {
    infinitive: "steal",
    pastSimple: "stole",
    pastParticiple: "stolen",
    translate: "воровать, красть",
  },
  {
    infinitive: "stick",
    pastSimple: "stuck",
    pastParticiple: "stuck",
    translate: "втыкать, приклеивать",
  },
  {
    infinitive: "strike",
    pastSimple: "struck",
    pastParticiple: "struck, stricken",
    translate: "ударять, бить, поражать",
  },
  {
    infinitive: "swear",
    pastSimple: "swore",
    pastParticiple: "sworn",
    translate: "клясться, присягать",
  },
  {
    infinitive: "sweep",
    pastSimple: "swept",
    pastParticiple: "swept",
    translate: "мести, подметать, смахивать",
  },
  {
    infinitive: "swim",
    pastSimple: "swam",
    pastParticiple: "swum",
    translate: "плавать, плыть",
  },
  {
    infinitive: "swing",
    pastSimple: "swung",
    pastParticiple: "swung",
    translate: "качаться, вертеться",
  },
  {
    infinitive: "take",
    pastSimple: "took",
    pastParticiple: "taken",
    translate: "брать, хватать, взять",
  },
  {
    infinitive: "teach",
    pastSimple: "taught",
    pastParticiple: "taught",
    translate: "учить, обучать",
  },
  {
    infinitive: "tear",
    pastSimple: "tore",
    pastParticiple: "torn",
    translate: "рвать, отрывать",
  },
  {
    infinitive: "tell",
    pastSimple: "told",
    pastParticiple: "told",
    translate: "рассказывать",
  },
  {
    infinitive: "think",
    pastSimple: "thought",
    pastParticiple: "thought",
    translate: "думать, мыслить, размышлять",
  },
  {
    infinitive: "throw",
    pastSimple: "threw",
    pastParticiple: "thrown",
    translate: "бросать, кидать, метать",
  },
  {
    infinitive: "understand",
    pastSimple: "understood",
    pastParticiple: "understood",
    translate: "понимать, постигать",
  },
  {
    infinitive: "wake",
    pastSimple: "woke",
    pastParticiple: "woken",
    translate: "просыпаться, будить",
  },
  {
    infinitive: "wear",
    pastSimple: "wore",
    pastParticiple: "worn",
    translate: "носить (одежду)",
  },
  {
    infinitive: "win",
    pastSimple: "won",
    pastParticiple: "won",
    translate: "победить, выиграть",
  },
  {
    infinitive: "write",
    pastSimple: "wrote",
    pastParticiple: "written",
    translate: "писать, записывать",
  },
];
